
package com.wizard.weather.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "weatherWS", targetNamespace = "http://impl.service.weather.wizard.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherWS {


    /**
     * 
     * @param cityName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getWeatherInfo", targetNamespace = "http://impl.service.weather.wizard.com/", className = "com.wizard.weather.service.impl.GetWeatherInfo")
    @ResponseWrapper(localName = "getWeatherInfoResponse", targetNamespace = "http://impl.service.weather.wizard.com/", className = "com.wizard.weather.service.impl.GetWeatherInfoResponse")
    @Action(input = "http://impl.service.weather.wizard.com/weatherWS/getWeatherInfoRequest", output = "http://impl.service.weather.wizard.com/weatherWS/getWeatherInfoResponse")
    public String getWeatherInfo(
        @WebParam(name = "cityName", targetNamespace = "")
        String cityName);

}
