
package com.wizard.weather.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-20T22:47:15.973+08:00
 * Generated source version: 3.3.5
 */
public final class WeatherService_WeatherWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.weather.wizard.com", "weatherWS");

    private WeatherService_WeatherWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WeatherWS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WeatherWS ss = new WeatherWS(wsdlURL, SERVICE_NAME);
        WeatherService port = ss.getWeatherWSPort();

        {
            System.out.println("Invoking getCitys...");
            java.lang.String _getCitys_provice = "";
            java.util.List<java.lang.String> _getCitys__return = port.getCitys(_getCitys_provice);
            System.out.println("getCitys.result=" + _getCitys__return);


        }
        {
            System.out.println("Invoking getWeatherInfo...");
            java.lang.String _getWeatherInfo_cityName = "";
            java.lang.String _getWeatherInfo__return = port.getWeatherInfo(_getWeatherInfo_cityName);
            System.out.println("getWeatherInfo.result=" + _getWeatherInfo__return);


        }

        System.exit(0);
    }

}
