package com.wizard.weather.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-20T23:38:39.996+08:00
 * Generated source version: 3.3.5
 */
@WebService(targetNamespace = "http://service.weather.wizard.com/", name = "WeatherService")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherService {

    @WebMethod
    @RequestWrapper(localName = "getCitys", targetNamespace = "http://service.weather.wizard.com/", className = "com.wizard.weather.service.GetCitys")
    @ResponseWrapper(localName = "getCitysResponse", targetNamespace = "http://service.weather.wizard.com/", className = "com.wizard.weather.service.GetCitysResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getCitys(

            @WebParam(name = "provice", targetNamespace = "")
                    java.lang.String provice
    );

    @WebMethod
    @RequestWrapper(localName = "getWeatherInfo", targetNamespace = "http://service.weather.wizard.com/", className = "com.wizard.weather.service.GetWeatherInfo")
    @ResponseWrapper(localName = "getWeatherInfoResponse", targetNamespace = "http://service.weather.wizard.com/", className = "com.wizard.weather.service.GetWeatherInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getWeatherInfo(

            @WebParam(name = "cityName", targetNamespace = "")
                    java.lang.String cityName
    );
}
